# Probability. Naive Bayes

In [1]:
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNBdf

In [3]:
df =pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [14]:
from sklearn.preprocessing import LabelEncoder
label_encoders = {}

for column in df.columns:
    label_encoder = LabelEncoder()
    df[column] = label_encoder.fit_transform(df[column])
    label_encoders[column] = label_encoder

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,5375,0,0,1,0,1,0,1,0,0,...,0,0,0,0,0,1,2,142,2505,0
1,3962,1,0,0,0,34,1,0,0,2,...,2,0,0,0,1,0,3,498,1466,0
2,2564,1,0,0,0,2,1,0,0,2,...,0,0,0,0,0,1,3,436,157,1
3,5535,1,0,0,0,45,0,1,0,2,...,2,2,0,0,1,0,0,266,1400,0
4,6511,0,0,0,0,2,1,0,1,0,...,0,0,0,0,0,1,2,729,925,1

In [15]:
X = df.drop(['Churn'], axis = 1)
y = df['Churn']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, test_size = 0.3)

## Gausian Naive Bayes

In [18]:
Gauss = GaussianNB()
Gauss.fit(X_train, y_train)
Gauss.score(X_test, y_test)

0.7586370089919545

## Multinomial Naive Bayes

In [19]:
Multinomial = MultinomialNB()
Multinomial.fit(X_train, y_train)
Multinomial.score(X_test, y_test)

0.6100331282536677

## Bernouli Naive Bayes

In [22]:
Bernoulli = BernoulliNB()
Bernoulli.fit(X_train, y_train)
Bernoulli.score(X_test, y_test)

0.747278750591576

In [25]:
tabel = pd.DataFrame(['Gauss', 'Multi', 'Bernoulli'], [Gauss.score(X_test, y_test), Multinomial.score(X_test, y_test), Bernoulli.score(X_test, y_test)])
tabel

                            0
Accuracy             ML Model
0.7586370089919545      Gauss
0.6100331282536677      Multi
0.747278750591576   Bernoulli